[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-volt"
version = "1.0.0"
description = "Django Volt Dashboard"
requires-python = ">=3.8"