# Generated by Django 5.2.1 on 2025-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelupload',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
