# Generated by Django 5.2.1 on 2025-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_excelupload_admin_notes_excelupload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelupload',
            name='processed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
