# Generated by Django 4.2.21 on 2025-05-15 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0004_alter_excelupload_processed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'Excel Upload', 'verbose_name_plural': 'Excel Uploads'},
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehousereceipt',
            name='packages',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='total_packages',
            field=models.CharField(max_length=100),
        ),
    ]
