# Generated by Django 4.2.21 on 2025-05-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_rename_receiver_waybill_consignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='receiver',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='consignee',
            field=models.CharField(default='', max_length=200),
        ),
    ]
