# Generated by Django 4.2.21 on 2025-05-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_waybill_receiver_alter_waybill_consignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waybill',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='waybill',
            name='consignee',
            field=models.CharField(max_length=200),
        ),
    ]
