# Generated by Django 4.2.21 on 2025-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_remove_waybill_receiver_alter_waybill_consignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
    ]
